### ISSUE TITLE
 TypeError: Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by q2192054** [ITJesse/UnblockNeteaseMusic#14]
Got this error message after start NeteaseMusic client

output:

Please set the username and password to enable the Web API.
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators ../../../usr/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/sequelize.js:236:13
Listening on port 8123
  <-- POST /api/linux/forward
Parse body failed.
Modify failed.
  --> POST /api/linux/forward 200 814ms 1.39kb
  <-- POST /api/linux/forward
  <-- POST /api/linux/forward
  <-- POST /api/linux/forward
  xxx POST /api/linux/forward 500 550ms -

  TypeError: Cannot read property 'code' of undefined
      at Function.fixJsonData (/usr/lib/node_modules/unblock-netease-music/dist/utils/netease/index.js:101:14)
      at errorHandler (/usr/lib/node_modules/unblock-netease-music/dist/app.js:58:32)
      at dispatch (/usr/lib/node_modules/unblock-netease-music/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/usr/lib/node_modules/unblock-netease-music/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at exports.proxy (/usr/lib/node_modules/unblock-netease-music/dist/middleware/proxy/index.js:59:11)
      at <anonymous>

Parse body failed.
Modify failed.
  --> POST /api/linux/forward 200 548ms 250b
  xxx POST /api/linux/forward 500 551ms -

  TypeError: Cannot read property 'code' of undefined
      at Function.fixJsonData (/usr/lib/node_modules/unblock-netease-music/dist/utils/netease/index.js:101:14)
      at errorHandler (/usr/lib/node_modules/unblock-netease-music/dist/app.js:58:32)
      at dispatch (/usr/lib/node_modules/unblock-netease-music/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/usr/lib/node_modules/unblock-netease-music/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at exports.proxy (/usr/lib/node_modules/unblock-netease-music/dist/middleware/proxy/index.js:59:11)
      at <anonymous>

  <-- POST /api/linux/forward
  xxx POST /api/linux/forward 500 721ms -

  TypeError: Cannot read property 'code' of undefined
      at Function.fixJsonData (/usr/lib/node_modules/unblock-netease-music/dist/utils/netease/index.js:101:14)
      at errorHandler (/usr/lib/node_modules/unblock-netease-music/dist/app.js:58:32)
      at dispatch (/usr/lib/node_modules/unblock-netease-music/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/usr/lib/node_modules/unblock-netease-music/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at exports.proxy (/usr/lib/node_modules/unblock-netease-music/dist/middleware/proxy/index.js:59:11)
      at <anonymous>

Ubuntu 17.04

**Comment by ITJesse** [comment]
What version of the UnblockNeteaseMusic you are using?
What version of the Node.js you are using?
What version of the NPM you are using?
What version of the NeteaseMusic you are using?

**Comment by q2192054** [comment]
unblockneteasemusic -V
3.0.7

node -v
v8.7.0

npm -v
5.4.2

 NeteaseMusic Client 

v1.0.0 (build 1026)

**Comment by ITJesse** [comment]
Thanks for report.
Now fixed.
