### ISSUE TITLE
关于安装的问题

### ISSUE THREAD

**Issue by mao13820** [ITJesse/UnblockNeteaseMusic#15]
您好，打扰了，想咨询您一下，我安装的时候老是显示root用户没有权限，导致无法安装，之后我在网上查找了一下，加了--unsafe-perm这个选项后可以安装了。
但是运行时又有如下提示，我尝试安装了一下sqlite，也不行，不知道该怎么办了，谢谢您了
root@vultr:~# unblockneteasemusic --username mht --password 950226
Web API enabled.
/usr/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31
        throw new Error('Please install sqlite3 package manually');
        ^

Error: Please install sqlite3 package manually
    at new ConnectionManager (/usr/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31:15)
    at new SqliteDialect (/usr/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/usr/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/sequelize.js:233:20)
    at Object.<anonymous> (/usr/lib/node_modules/unblock-netease-music/dist/models/index.js:30:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/unblock-netease-music/dist/controllers/modify/dead.js:8:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/unblock-netease-music/dist/controllers/modify/player.js:12:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/unblock-netease-music/dist/controllers/modify/index.js:7:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/unblock-netease-music/dist/controllers/index.js:8:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/unblock-netease-music/dist/app.js:39:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

**Comment by ITJesse** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by AndyChen2005121** [comment]
没错，我也是这个问题
