### ISSUE TITLE
#18 Still reproducible with 3.1.3

### ISSUE THREAD

**Issue by freeyoung** [ITJesse/UnblockNeteaseMusic#19]
Hi,

I've upgraded to unblockneteasemusic 3.1.3 but it seems #18 is still reproducible from my side.

```
$ unblockneteasemusic -p 64310 -v
Please set the username and password to enable the Web API.
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
Listening on port 64310
Executing (default): CREATE TABLE IF NOT EXISTS `Recents` (`songId` INTEGER PRIMARY KEY, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): CREATE TABLE IF NOT EXISTS `Pairs` (`songId` INTEGER PRIMARY KEY, `plugin` VARCHAR(255), `name` VARCHAR(255), `artist` VARCHAR(255), `album` VARCHAR(255), `albumPic` VARCHAR(255), `hash` VARCHAR(255), `createdAt` DATETIME, `updatedAt` DATETIME);
Executing (default): CREATE TABLE IF NOT EXISTS `Songs` (`songId` INTEGER PRIMARY KEY, `name` VARCHAR(255), `artist` VARCHAR(255), `album` VARCHAR(255), `albumPic` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Recents`)
Executing (default): PRAGMA INDEX_LIST(`Pairs`)
Executing (default): PRAGMA INDEX_LIST(`Songs`)
  <-- POST /eapi/song/enhance/player/url
Cannot get orignal response.
  xxx POST /eapi/song/enhance/player/url 500 100ms -

  Error: Error: StatusCodeError: 403 - {"type":"Buffer","data":[60,104,116,109,108,62,13,10,60,104,101,97,100,62,60,116,105,116,108,101,62,52,48,51,32,70,111,114,98,105,100,100,101,110,60,47,116,105,116,108,101,62,60,47,104,101,97,100,62,13,10,60,98,111,100,121,32,98,103,99,111,108,111,114,61,34,119,104,105,116,101,34,62,13,10,60,99,101,110,116,101,114,62,60,104,49,62,52,48,51,32,70,111,114,98,105,100,100,101,110,60,47,104,49,62,60,47,99,101,110,116,101,114,62,13,10,60,104,114,62,60,99,101,110,116,101,114,62,110,103,105,110,120,60,47,99,101,110,116,101,114,62,13,10,60,47,98,111,100,121,62,13,10,60,47,104,116,109,108,62,13,10]}
      at _callee$ (/usr/lib/node_modules/unblock-netease-music/dist/middleware/proxy/index.js:100:19)
      at tryCatch (/usr/lib/node_modules/unblock-netease-music/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (/usr/lib/node_modules/unblock-netease-music/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as throw] (/usr/lib/node_modules/unblock-netease-music/node_modules/regenerator-runtime/runtime.js:114:21)
      at step (/usr/lib/node_modules/unblock-netease-music/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/lib/node_modules/unblock-netease-music/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
      at <anonymous>

  <-- POST /eapi/song/enhance/player/url
Cannot get orignal response.
  xxx POST /eapi/song/enhance/player/url 500 71ms -

  Error: Error: StatusCodeError: 403 - {"type":"Buffer","data":[60,104,116,109,108,62,13,10,60,104,101,97,100,62,60,116,105,116,108,101,62,52,48,51,32,70,111,114,98,105,100,100,101,110,60,47,116,105,116,108,101,62,60,47,104,101,97,100,62,13,10,60,98,111,100,121,32,98,103,99,111,108,111,114,61,34,119,104,105,116,101,34,62,13,10,60,99,101,110,116,101,114,62,60,104,49,62,52,48,51,32,70,111,114,98,105,100,100,101,110,60,47,104,49,62,60,47,99,101,110,116,101,114,62,13,10,60,104,114,62,60,99,101,110,116,101,114,62,110,103,105,110,120,60,47,99,101,110,116,101,114,62,13,10,60,47,98,111,100,121,62,13,10,60,47,104,116,109,108,62,13,10]}
      at _callee$ (/usr/lib/node_modules/unblock-netease-music/dist/middleware/proxy/index.js:100:19)
      at tryCatch (/usr/lib/node_modules/unblock-netease-music/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (/usr/lib/node_modules/unblock-netease-music/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as throw] (/usr/lib/node_modules/unblock-netease-music/node_modules/regenerator-runtime/runtime.js:114:21)
      at step (/usr/lib/node_modules/unblock-netease-music/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/lib/node_modules/unblock-netease-music/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
      at <anonymous>

[..omitted]
```

```
$ unblockneteasemusic --version
3.1.3
```

I'm using the macOS client, version `1.4.3`.

Node and npm versions are as follows:

```
$ node -v
v8.11.1
$ npm -v
5.6.0
```

**Comment by ITJesse** [comment]
Maybe you should try 1.5.9 (622).
I think the old API without encrypt is closed in this time.

Please follow the instruction of [NeteaseMusicPlugin](https://github.com/ITJesse/NeteaseMusicPlugin).

**Comment by freeyoung** [comment]
1.5.9 + NeteaseMusicPlugin combo seems working well for most of my playlists. Redirecting to QQMusic seems broken (status code 200, checking the verbose log), but that is fine for the time being.

Thanks a lot.

**Comment by leewp14** [comment]
with 1.5.9, it is not retuning any error on linux, but client couldn't load properly (infinite loading + open playlists from home screen will straight go back to home)

**Comment by rexx0520** [comment]
it's not working again...

**Comment by ITJesse** [comment]
I fixed the QQ Music plugin in the latest commit.
Have fun :)
