### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by steven7851** [ITJesse/UnblockNeteaseMusic#6]
我用 Linode 架设的 server，使用 Windows client v1.9.4
是我没有设置好？还是 Linode 不能用？
```
root@debian:~# unblockneteasemusic -p 8123 -k -q -r
Rewrite music download url.
Finding copyright music on Kugou.
Finding copyright music on QQ Music.
Listening on port 8123
QQ Music module is ready.
  <-- POST http://music.163.com/eapi/subcount
  <-- POST http://music.163.com/eapi/batch
  xxx POST http://music.163.com/eapi/subcount 500 15ms -

  Error: getaddrinfo ENOTFOUND 223.252.199.7http 223.252.199.7http:80
      at errnoException (dns.js:28:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

  xxx POST http://music.163.com/eapi/batch 500 10ms -

  Error: getaddrinfo ENOTFOUND 223.252.199.7http 223.252.199.7http:80
      at errnoException (dns.js:28:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by ITJesse** [comment]
海外架设请在服务器上运行
```
nslookup music.163.com
```
将获得的 IP 作为启动参数 `--force-ip <ip>`
但是并不推荐这样做，大量歌曲会使用 QQ Music 搜索
推荐的做法是部署在境内

**Comment by ITJesse** [comment]
我看你的日志貌似是把 IP 当做域名解析了，能否提供下你的 DNS 服务器地址，以及 node 版本？
目前无法重现这个问题。

**Comment by steven7851** [comment]
因为我的 sniproxy 一直弄不好，因此用proxy代理 music.163.com 到我的 server_ip:8123
我大概知道问题在哪了，谢谢
